### ISSUE TITLE
why do you have 2 repos?

### ISSUE THREAD

**Issue by Silur** [WhisperSystems/libsignal-protocol-java#26]
There is this repo and https://github.com/WhisperSystems/libsignal-service-java. what's the difference? Both are java implementations of the protocol, both from the same team, why not focus all resources into one product instead split it to two?

**Comment by moxie0** [comment]
Thanks but this isn't a discussion forum, please do not post questions here.

**Comment by malkusch** [comment]
It's just a question which should be easy to answer for you. I also don't understand the relation between those two implentations. I'm totally confused which I should use. So a bit clarification about the intended use cases would be really appreciated.
