### ISSUE TITLE
gradle build fails based on unknown variables {sonatypeRepo,userName, password}

### ISSUE THREAD

**Issue by quantum-fusion** [WhisperSystems/libsignal-protocol-java#40]
The problem is when I try to build, using $gradle build

This is the error:
* What went wrong:
A problem occurred evaluating project ':java'.
> Could not get unknown property 'sonatypeRepo' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

https://github.com/WhisperSystems/libsignal-protocol-java/blob/4f5e1ff299cea22cc75bb97249020a7da67b816d/java/build.gradle#L50

The issues are as follows: sonatypeRepo is unknown, and userName and password are also unknown, therefore gradle fails in the build step.

repository(url: sonatypeRepo) {
            authentication(userName: whisperSonatypeUsername, password: whisperSonatypePassword)
        }

**Comment by moxie0** [comment]
You can define the variables if you'd like. In the future, for questions about setting up a build environment, please see the online forums.

**Comment by iamcxl369** [comment]
@moxie0  where is the online forums? thanks

**Comment by He-Ro** [comment]
https://community.signalusers.org/
