### ISSUE TITLE
REST API Server integration with pom.xml and enhancements

### ISSUE THREAD

**Issue by quantum-fusion** [WhisperSystems/libsignal-protocol-java#41]
I want to be able to build this project, and others similar like it using maven, for server side java, for encrypt, decrypt, and Hmac for authenticated diffie hellman, and am considering adding your Hmac implementation to mine.  I want to eliminate having to generate RSA public keys manually from command line.

I want the server side REST APIs to use Diffie hellman, along with the encrypt,decrypt, and hmac, for authenticated transactions.

Is it a possibility to add maven pom.xml support to these projects, along with a Diffie Hellman implementation?  I have one to offer. (see https://github.com/quantum-fusion/aes-256-encryption-utility/blob/e6d4f1166a3a94fde6a6f9025b551fdc0e1f18d7/src/test/java/com/acquitygroup/encryption/AESCipherTest.java#L60 )

I am also interested in adding create JWT, create JWE, and decrypt JWE. 
(see https://github.com/quantum-fusion/aes-256-encryption-utility/blob/e6d4f1166a3a94fde6a6f9025b551fdc0e1f18d7/src/main/java/com/acquitygroup/encryption/CryptoHelper.java#L56 )

**Comment by quantum-fusion** [comment]
.

**Comment by quantum-fusion** [comment]
The goal of this is to offer an authenticated diffie hellman transaction using Hmac for authentication of the transaction, in a simple protocol that allows transmission of JWE tokens over an encrypted channel for SpringBoot RESTAPI implementions that support AWS Lambda and SpringBoot like (see https://github.com/quantum-fusion/springboot_swagger_example-master-cassandra)

**Comment by moxie0** [comment]
Thanks but we're not going to do this. In the future if you have questions or discussion topics, please see the community forums.
